#!/bin/bash
#
# generate python files based on the designer ui files
#

mkdir -p KnowledgeKeeper/forms
PYUIC=$(which pyuic4)
PYRCC=$(which pyrcc4)

[ -z $PYUIC ] && echo "can't find pyuic4" && exit 1
[ -z $PYRCC ] && echo "can't find pyrcc4" && exit 1

init=KnowledgeKeeper/forms/__init__.py
temp=KnowledgeKeeper/forms/scratch
rm -f $init $temp
echo "# This file auto-generated by build_ui.sh. Don't edit." > $init
echo "__all__ = [" >> $init

echo "Generating forms.."
for i in designer/*.ui
do
    base=$(echo $i | perl -pe 's/\.ui//; s%designer/%%;')
    py=$(echo $i | perl -pe 's/\.ui/.py/; s%designer%KnowledgeKeeper/forms%;')
    echo " * "$py
    $PYUIC $i -o $py
    echo "	\"$base\"," >> $init
    echo "import $base" >> $temp
    # munge the output to use gettext
#    perl -pi.bak -e 's/QtGui.QApplication.translate\(".*?", /_(/; s/, None, QtGui.*/))/' $py
    # remove the 'created' time, to avoid flooding the version control system
    perl -pi.bak -e 's/^# Created:.*$//' $py
    rm $py.bak
done
echo "]" >> $init
cat $temp >> $init
rm $temp

echo "Building resources.."
$PYRCC icons.qrc -o icons_rc.py
